// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpfsensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSensor returns the embedded CollectionSpec for sensor.
func loadSensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sensor: %w", err)
	}

	return spec, err
}

// loadSensorObjects loads sensor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sensorObjects
//	*sensorPrograms
//	*sensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSensorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorSpecs struct {
	sensorProgramSpecs
	sensorMapSpecs
	sensorVariableSpecs
}

// sensorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorProgramSpecs struct {
	GwSensor *ebpf.ProgramSpec `ebpf:"gw_sensor"`
}

// sensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// sensorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorVariableSpecs struct {
}

// sensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorObjects struct {
	sensorPrograms
	sensorMaps
	sensorVariables
}

func (o *sensorObjects) Close() error {
	return _SensorClose(
		&o.sensorPrograms,
		&o.sensorMaps,
	)
}

// sensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *sensorMaps) Close() error {
	return _SensorClose(
		m.Events,
	)
}

// sensorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorVariables struct {
}

// sensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorPrograms struct {
	GwSensor *ebpf.Program `ebpf:"gw_sensor"`
}

func (p *sensorPrograms) Close() error {
	return _SensorClose(
		p.GwSensor,
	)
}

func _SensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sensor_x86_bpfel.o
var _SensorBytes []byte
